# Basic Numpy Functions

In [1]:
import numpy as np
array=np.array([[2,3,4,5,6],[1,2,3,4,5]])
print(array)

[[2 3 4 5 6]
 [1 2 3 4 5]]


In [2]:
array*array

array([[ 4,  9, 16, 25, 36],
       [ 1,  4,  9, 16, 25]])

In [3]:
array+array

array([[ 4,  6,  8, 10, 12],
       [ 2,  4,  6,  8, 10]])

In [4]:
array-array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
array/array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
1/array+array*2

array([[ 4.5       ,  6.33333333,  8.25      , 10.2       , 12.16666667],
       [ 3.        ,  4.5       ,  6.33333333,  8.25      , 10.2       ]])

In [7]:
array**array

array([[    4,    27,   256,  3125, 46656],
       [    1,     4,    27,   256,  3125]], dtype=int32)

# Slicing

In [8]:
array2=np.array([2,3,4,5,6])
array2[1]

3

In [9]:
arr=array2[2:5]
arr

array([4, 5, 6])

In [10]:
arr[0]=10

In [11]:
array2

array([ 2,  3, 10,  5,  6])

In [12]:
arr2=array2[2:5].copy()

In [13]:
arr2[0]=15
array2

array([ 2,  3, 10,  5,  6])

In [14]:
arr2

array([15,  5,  6])

In [15]:
array

array([[2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [16]:
array[0,3]

5

# Sorting and Shaping in Numpy

In [17]:
a=np.array([1,2,3,45,6,7,1,2,0,8,9,3,5,7,1,3,6,9])
a.shape

(18,)

In [18]:
a=a.reshape(6,3)

In [19]:
np.argsort(a)

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1],
       [2, 0, 1],
       [2, 0, 1],
       [0, 1, 2]], dtype=int32)

In [20]:
np.argmin(a)

8

In [21]:
np.argmax(a)

3