# Basic in Numpy

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
list1=list(range(10))

In [3]:
import numpy as np

In [4]:
arr=np.arange(10)

In [5]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
for _ in range(10):
    print([item*3 for item in list1])

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]


In [8]:
for _ in range(10):
    print(arr*3) 

[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]
[ 0  3  6  9 12 15 18 21 24 27]


In [11]:
array=np.array([[2,3,4,4,5.4],[3,4,5,5,0.9]],dtype='int64')
print("shape:-",array.shape,"\n")
print("dtype:-",array.dtype,"\n")
print("array:-\n",array)

shape:- (2, 5) 

dtype:- int64 

array:-
 [[2 3 4 4 5]
 [3 4 5 5 0]]


np.zeros(4,dtype='int32')